# Generated by Django 4.1.2 on 2022-10-11 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='Abbreviation')),
                ('name', models.CharField(max_length=60, verbose_name='Type name')),
            ],
            options={
                'verbose_name': 'Cost Type',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=30, verbose_name='Reference')),
            ],
            options={
                'verbose_name': 'Fund',
            },
        ),
        migrations.CreateModel(
            name='Fund_Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10, verbose_name='Funder abbreviation')),
                ('name', models.CharField(max_length=60, verbose_name='Funder Name')),
            ],
            options={
                'verbose_name': 'Funder Institution',
            },
        ),
        migrations.CreateModel(
            name='Fund_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund', verbose_name='Related Fund')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.cost_type', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Fund Line',
            },
        ),
        migrations.AddField(
            model_name='fund',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund_institution', verbose_name='Fund Instituition'),
        ),
        migrations.AddField(
            model_name='fund',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.institution', verbose_name='Manager Institution'),
        ),
        migrations.AddField(
            model_name='fund',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Funded Project'),
        ),
    ]
