# Generated by Django 4.1.2 on 2022-10-08 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fund_Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Fund_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.cost_type')),
            ],
        ),
        migrations.AddField(
            model_name='fund',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund_institution'),
        ),
        migrations.AddField(
            model_name='fund',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.institution'),
        ),
        migrations.AddField(
            model_name='fund',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
