# Generated by Django 4.1.2 on 2022-10-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='ref',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
