# Generated by Django 4.1.2 on 2022-10-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_cost_type_level_cost_type_lft_cost_type_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='fund',
            name='start_date',
            field=models.DateField(default='2000-1-1', verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
