# Generated by Django 4.1.2 on 2022-10-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_fund_end_date_fund_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fund_item',
            unique_together={('type', 'fund')},
        ),
    ]
