# Generated by Django 4.1.2 on 2022-10-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_alter_fund_item_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
