email:
  backend: 'django.core.mail.backends.smtp.EmailBackend'
  host: ''
  port: 25
  username: ''
  password: ''
  sender: ''
  tls: False
  ssl: False

django_admins: ''  # string of username:email username2:email2

site_id: 1

django_allowed_hosts: '' # separator is space

debug: true
log_level: 'WARNING'
secret_key: '12345678910abcdefghijklmnopqrstuvwxyz@django_secretkey'
csrf_trusted_origins: ''

# # Configure DB
# lab_db_name: ''
# lab_db_user: ''
# lab_db_password: ''
# lab_db_host: ''
# lab_db_port: ''

## admin site customisation
admin_header: "LabsManager"
admin_site_title: "LabsManager"
admin_index_title: "Menu"


static_root: '/home/labsmanager/data/static/'
media_root: "/home/labsmanager/data/media/"
plugin_dir: '/home/labsmanager/data/plugin/'
plugin_enable: 'false'
# CSP policy
admin_use_csp: 'true'
#admin_csp_default: "site1.com, site2.com"
admin_csp_script: "'unsafe-inline','unsafe-eval'"
admin_csp_style: "'unsafe-inline'"
admin_csp_font: "'unsafe-inline','unsafe-eval', data:"
admin_csp_data: "'unsafe-inline','unsafe-eval'"
admin_csp_img: "data:"
# admin_csp_media: ""

#security issues 
csrf_cookie_secure: 'true'
csrf_cookie_samesite: 'Strict'
session_cookie_secure: 'false'
secure_browser_xss_filter: 'true'
secure_content_type_nosniff: 'true'
secure_ssl_redirect: 'false'
x_frame_options: 'DENY'
secure_hsts_seconds: 300
secure_hsts_include_subdomains: 'true'
secure_hsts_preload: 'true'

# Cookie lifespan when logged
session_cookie_age = 12800