# Generated by Django 4.1.2 on 2022-10-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_employee_type_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_status',
            name='is_contractual',
            field=models.CharField(choices=[('c', 'Contractual'), ('s', 'Statutory'), ('p', 'Projected')], default='c', max_length=1, verbose_name='Is Contractual'),
        ),
    ]
