# Generated by Django 4.1.2 on 2022-10-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_employee_type_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employee'},
        ),
        migrations.AlterModelOptions(
            name='employee_status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='employee_type',
            options={'verbose_name': 'Employee Type'},
        ),
        migrations.RemoveField(
            model_name='employee_status',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee_status',
            name='employee',
            field=models.ManyToManyField(to='staff.employee'),
        ),
    ]
