# Generated by Django 4.1.2 on 2022-10-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_employee_status_is_contractual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_status',
            name='is_contractual',
            field=models.CharField(choices=[('c', 'Contractual'), ('s', 'Statutory')], default='c', max_length=1, verbose_name='Is Contractual'),
        ),
    ]
