# Generated by Django 4.1.2 on 2022-10-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_employee_status_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_status',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee_status',
            name='employee',
            field=models.ManyToManyField(to='staff.employee'),
        ),
    ]
