# Generated by Django 4.1.2 on 2022-10-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_valid',
            new_name='is_active',
        ),
    ]
