# Generated by Django 4.1.2 on 2022-10-08 05:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fund', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('e', 'Engaged'), ('r', 'Realised'), ('p', 'Projected')], default='e', max_length=1)),
                ('fund_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.cost_type')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('quotity', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_expense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expense.expense')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.contract')),
            ],
            bases=('expense.expense',),
        ),
    ]
