# Generated by Django 4.1.2 on 2022-10-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amout',
            new_name='amount',
        ),
    ]
