# Generated by Django 4.1.2 on 2022-10-08 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_alter_fund_ref'),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='fund',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fund.fund'),
            preserve_default=False,
        ),
    ]
