# Generated by Django 4.1.2 on 2022-10-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_amout_expense_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Type name')),
            ],
            options={
                'verbose_name': 'Contract Type',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ManyToManyField(to='expense.contract_type', verbose_name='Contract Type'),
        ),
    ]
