# Generated by Django 4.1.2 on 2022-10-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_contract_type_contract_contract_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_type',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.contract_type', verbose_name='Contract Type'),
        ),
    ]
