# Generated by Django 4.1.2 on 2022-10-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution_participant',
            name='status',
            field=models.CharField(choices=[('c', 'Coordinator'), ('p', 'Participant')], default='p', max_length=1),
        ),
    ]
