# Generated by Django 4.1.2 on 2022-10-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('l', 'Leader'), ('cl', 'Co Leader'), ('p', 'Participant')], default='p', max_length=2, verbose_name='Status'),
        ),
    ]
