# Generated by Django 4.1.2 on 2022-10-20 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_participant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='quotity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Time qutotity'),
        ),
    ]
