# Generated by Django 4.1.2 on 2022-10-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_participant_quotity'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='participant',
            name='start_date',
            field=models.DateField(default='2010-1-1', verbose_name='Start Date'),
            preserve_default=False,
        ),
    ]
