# Generated by Django 4.1.2 on 2022-10-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_participant_end_date_participant_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institution_participant',
            unique_together={('project', 'institution')},
        ),
    ]
